services:
  lots-service:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT-5432}/${DB_DATABASE}?SCHEMA=public&connection_limit=${DB_CONNECTION_LIMIT-20}
      IDENTITY_SERVICE_URL: ${IDENTITY_SERVICE_URL}
      RESERVATIONS_SERVICE_URL: ${RESERVATIONS_SERVICE_URL}
    ports:
      - ${LOTS_SERVICE_PORT-3000}:3000
    depends_on:
      lots-service-db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./drizzle:/usr/src/app/drizzle

  lots-service-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - lots-db-data:/var/lib/postgresql/data
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${LOTS_SERVICE_DB_PORT-5432}:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  lots-db-data:
