apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          env:
            - name: DB_URL
              value: postgresql://identityservice:identityservicedbpassword@identity-db:5432/identityservicedb?SCHEMA=public&connection_limit=20
          image: josejaime5271/parker-identity-service
          ports:
            - containerPort: 3000
              protocol: TCP
