apiVersion: v1
kind: Service
metadata:
  name: identity-service-service
spec:
  selector:
    app: identity-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP

