apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
  labels:
    app: identity-db
spec:
  selector:
    matchLabels:
      app: identity-db
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
        - name: identity-db
          image: postgres:17
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: identityservicedb
            - name: POSTGRES_USER
              value: identityservice
            - name: POSTGRES_PASSWORD
              value: identityservicedbpassword
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: identity-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: identity-db-storage
          persistentVolumeClaim:
            claimName: identity-db-pvc
      restartPolicy: Always
