apiVersion: v1
kind: Service
metadata:
  name: identity-db
spec:
  selector:
    app: identity-db
  type: ClusterIP
  ports:
  - name: identity-db
    protocol: TCP
    port: 5432
    targetPort: 5432
