apiVersion: v1
kind: Service
metadata:
  name: reservations-service
spec:
  selector:
    app: reservations-service
  ports:
    - name: reservations-service
      port: 3000
      targetPort: 3000
  type: ClusterIP

