services:
  reservations-service:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST-reservations-service-db}:${DB_PORT-5432}/${DB_DATABASE}?SCHEMA=public&connection_limit=${DB_CONNECTION_LIMIT-20}
      GOOGLE_APPLICATION_CREDENTIALS: '/usr/src/app/src/firebase/credentials/service-account-file.json'
      RABBITMQ_URL: 'amqp://rabbitmq:5672'
    ports:
      - ${RESERVATIONS_SERVICE_PORT-3000}:3000
    depends_on:
      reservations-service-db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./drizzle:/usr/src/app/drizzle

  reservations-service-db:
    image: 'postgres:17'
    volumes:
      - reservations-db-data:/var/lib/postgresql/data
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${RESERVATIONS_SERVICE_DB_PORT-5432}:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: 'rabbitmq:4'

volumes:
  reservations-db-data:
